# Generated by Django 4.2.3 on 2023-08-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('product_description', models.CharField(max_length=150, verbose_name='Описание')),
                ('product_preview', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Превью')),
                ('product_category', models.CharField(max_length=150, verbose_name='Категория')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_changing', models.DateField(auto_now=True, verbose_name='Дата последнего изменения')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('product_name',),
            },
        ),
    ]
