# Generated by Django 4.2.4 on 2023-08-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_product_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('blog_text', models.CharField(max_length=150, verbose_name='Содержимое')),
                ('blog_preview', models.ImageField(blank=True, null=True, upload_to='catalog/', verbose_name='Превью')),
                ('blog_slug', models.CharField(blank=True, max_length=150, null=True, verbose_name='slug')),
                ('blog_date_creation', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('blog_is_active', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('blog_views_count', models.IntegerField(default=0, verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ('blog_title',),
            },
        ),
    ]
