# Generated by Django 4.2.4 on 2023-08-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_text',
            field=models.TextField(verbose_name='Содержимое'),
        ),
    ]
