# Generated by Django 4.2.3 on 2023-08-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'активная'), (False, 'не активная')], verbose_name='Текущая версия'),
        ),
    ]
