# Generated by Django 4.2.3 on 2023-09-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'опубликован'), (False, 'не опубликован')], default=False, verbose_name='Публикация продукта'),
        ),
    ]
